DROP TABLE PLAYER_POSITIONS;
DROP TABLE GAMES_TEAMS_STATISTICS;
DROP TABLE GAMES;
DROP TABLE GAME_STATISTICS;
DROP TABLE PLAYERS_TEAMS_STATISTICS;
DROP TABLE TEAMS;
DROP TABLE ARENAS;
DROP TABLE LOCATIONS;
DROP TABLE PLAYERS;
DROP TABLE PLAYER_STATISTICS;
--DELETE SEQUENCES FROM RECYCLE BIN
PURGE RECYCLEBIN;