/*1*/
SELECT DISTINCT PLAYERS.PLAYER_NAME "PLAYER NAME" , PLAYERS.PLAYER_AGE "PLAYER AGE"
FROM PLAYERS_TEAMS_STATISTICS
JOIN PLAYERS ON PLAYERS_TEAMS_STATISTICS.PLAYER_ID = PLAYERS.PLAYER_ID
JOIN TEAMS ON PLAYERS_TEAMS_STATISTICS.TEAM_ID = TEAMS.TEAM_ID
WHERE TEAMS.TEAM_ACRONYM = 'CHO' OR TEAMS.TEAM_ACRONYM = 'GSW';

/*2*/
SELECT PLAYERS.PLAYER_NAME "PLAYER NAME", AVG(PLAYER_STATISTICS.PTS) "AVERAGE POINTS"
FROM PLAYERS_TEAMS_STATISTICS
JOIN PLAYER_STATISTICS ON PLAYERS_TEAMS_STATISTICS.STATISTICS_ID = PLAYER_STATISTICS.STATS_ID
JOIN PLAYERS ON PLAYERS_TEAMS_STATISTICS.PLAYER_ID = PLAYERS.PLAYER_ID
WHERE PLAYER_NAME = 'Stephen Curry'
GROUP BY PLAYERS.PLAYER_NAME;

/*3*/
SELECT DISTINCT TEAMS.TEAM_NAME "TEAM" , AVG(GAME_STATISTICS.POINTS) "AVERAGE POINTS CONCEDED"
FROM GAME_STATISTICS
JOIN GAMES_TEAMS_STATISTICS ON GAME_STATISTICS.STATS_ID = GAMES_TEAMS_STATISTICS.STATS_ID
JOIN GAMES ON GAMES_TEAMS_STATISTICS.GAME_ID  = GAMES.GAME_ID AND GAMES_TEAMS_STATISTICS.TEAM_ID = GAMES.AWAY_TEAM
JOIN TEAMS ON GAMES.HOME_TEAM = TEAMS.TEAM_ID
WHERE TEAMS.TEAM_ACRONYM = 'MIL'
GROUP BY TEAMS.TEAM_NAME;

/*4*/
SELECT HOME_TEAMS.TEAM_NAME                    "HOME TEAM",
       AWAY_TEAMS.TEAM_NAME                    "AWAY TEAM",
       GAMES.GAME_DATE                         "DATE",
       GAME_STATISTICS.X3POINTSHOTS_PERCENTAGE "3 POINTS PERCENTAGE"
FROM GAMES_TEAMS_STATISTICS
JOIN GAMES ON GAMES_TEAMS_STATISTICS.GAME_ID = GAMES.GAME_ID
JOIN TEAMS ON GAMES_TEAMS_STATISTICS.TEAM_ID = TEAMS.TEAM_ID
JOIN TEAMS HOME_TEAMS ON GAMES.HOME_TEAM = HOME_TEAMS.TEAM_ID
JOIN TEAMS AWAY_TEAMS ON GAMES.AWAY_TEAM = AWAY_TEAMS.TEAM_ID
JOIN GAME_STATISTICS ON GAMES_TEAMS_STATISTICS.STATS_ID = GAME_STATISTICS.STATS_ID
WHERE TEAMS.TEAM_ACRONYM = 'DAL'
ORDER BY GAME_STATISTICS.X3POINTSHOTS_PERCENTAGE DESC
FETCH FIRST 1 ROWS WITH TIES;


/*5*/
SELECT HOME_TEAMS.TEAM_ACRONYM                      "HOME",
       AWAY_TEAMS.TEAM_ACRONYM                      "AWAY",
       GAME_DATE                                    "DATE",
       HOME_G_STAT.POINTS                           "HOME POINTS",
       AWAY_G_STAT.POINTS                           "AWAY POINTS",
       ABS(HOME_G_STAT.POINTS - AWAY_G_STAT.POINTS) "DIFFERENCE"
FROM GAMES
JOIN TEAMS HOME_TEAMS ON GAMES.HOME_TEAM = HOME_TEAMS.TEAM_ID
JOIN TEAMS AWAY_TEAMS ON GAMES.AWAY_TEAM = AWAY_TEAMS.TEAM_ID
JOIN GAME_STATISTICS HOME_G_STAT ON HOME_G_STAT.STATS_ID =
                                    (
                                        /*JOIN THE STATS THAT MATCH THE STATS OF THE HOME TEAM IN EVERY GAME*/
                                        SELECT GAMES_TEAMS_STATISTICS.STATS_ID
                                        FROM GAMES_TEAMS_STATISTICS
                                        WHERE GAMES_TEAMS_STATISTICS.GAME_ID = GAMES.GAME_ID
                                        AND   GAMES_TEAMS_STATISTICS.TEAM_ID = GAMES.HOME_TEAM
                                    )
JOIN GAME_STATISTICS AWAY_G_STAT ON AWAY_G_STAT.STATS_ID =
                                    (
                                        /*JOIN THE STATS THAT MATCH THE STATS OF THE AWAY TEAM IN EVERY GAME*/
                                        SELECT GAMES_TEAMS_STATISTICS.STATS_ID
                                        FROM GAMES_TEAMS_STATISTICS
                                        WHERE GAMES_TEAMS_STATISTICS.GAME_ID = GAMES.GAME_ID
                                        AND   GAMES_TEAMS_STATISTICS.TEAM_ID = GAMES.AWAY_TEAM
                                    )
ORDER BY DIFFERENCE DESC
FETCH FIRST 1 ROWS WITH TIES;
