--arenas.csv

DECLARE
    LOC_ID NUMBER(3);
BEGIN
    SELECT LOCATION_ID
    INTO LOC_ID
    FROM LOCATIONS
    WHERE LOCATION_CITY = 'Atlanta'
    AND LOCATION_STATE = 'Georgia';

    INSERT INTO ARENAS (ARENA_NAME,ARENA_LOCATION)
    VALUES ('State Farm Arena',LOC_ID);
    COMMIT;
END;
