ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MM-YYYY HH24:MI:SS';

DECLARE
    HOME_TEAM_ID  NUMBER(3);
    AWAY_TEAM_ID  NUMBER(3);
    GA_ID         NUMBER(5);
    GA_STATS      NUMBER(6);
BEGIN
    SELECT TEAM_ID
    INTO HOME_TEAM_ID
    FROM TEAMS
    WHERE TEAM_ACRONYM = 'BOS';

    SELECT TEAM_ID
    INTO AWAY_TEAM_ID
    FROM TEAMS
    WHERE TEAM_ACRONYM = 'CLE';

    INSERT INTO GAMES (GAME_DATE, HOME_TEAM, AWAY_TEAM)
    VALUES ('28/10/2014', HOME_TEAM_ID, AWAY_TEAM_ID)
    RETURNING GAME_ID INTO GA_ID;

    INSERT INTO GAME_STATISTICS (GAME_NUMBER, TEAM_RESULT, POINTS, FIELD_GOALS, FIELD_GOALS_ATTEMPTED,
                                 FIELD_GOALS_PERCENTAGE, X3POINTSHOTS, X3POINTSHOTS_ATTEMPTED, X3POINTSHOTS_PERCENTAGE,
                                 FREETHROWS, FREETHROWS_ATTEMPTED, FREETHROWS_PERCENTAGE, OFFREBOUNDS, TOTALREBOUNDS,
                                 ASSISTS, STEALS, BLOCKS, TURNOVERS, TOTALFOULS)
    VALUES (90, 'W', 121, 48, 88, 0.545, 6, 20, 0.3, 19, 23, 0.826, 8, 39, 32, 7, 1, 14, 26) RETURNING STATS_ID INTO GA_STATS;
    
    INSERT INTO GAMES_TEAMS_STATISTICS(GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID, HOME_TEAM_ID, GA_STATS);

    INSERT INTO GAME_STATISTICS (GAME_NUMBER, TEAM_RESULT, POINTS, FIELD_GOALS, FIELD_GOALS_ATTEMPTED,
                                 FIELD_GOALS_PERCENTAGE, X3POINTSHOTS, X3POINTSHOTS_ATTEMPTED, X3POINTSHOTS_PERCENTAGE,
                                 FREETHROWS, FREETHROWS_ATTEMPTED, FREETHROWS_PERCENTAGE, OFFREBOUNDS, TOTALREBOUNDS,
                                 ASSISTS, STEALS, BLOCKS, TURNOVERS, TOTALFOULS)
    VALUES (90, 'L', 121, 48, 88, 0.545, 6, 20, 0.3, 19, 23, 0.826, 8, 39, 32, 7, 1, 14, 26) RETURNING STATS_ID INTO GA_STATS;

    INSERT INTO GAMES_TEAMS_STATISTICS(GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID, AWAY_TEAM_ID, GA_STATS);

    COMMIT;
END;
