DECLARE
    PL_ID NUMBER(3);
    TE_ID NUMBER(3);
    ST_ID NUMBER(3);
BEGIN
	/* INSERT PLAYER BASIC INFO */
	INSERT INTO PLAYERS (PLAYER_NAME,PLAYER_AGE)
	VALUES ('Omer Asik',31)
	RETURNING PLAYER_ID INTO PL_ID;

	/*THIS COVERS THE PLAYERS CAREER IN TOR*/
    SELECT TEAM_ID
    INTO TE_ID
    FROM TEAMS
    WHERE TEAM_ACRONYM = 'TOR';

    INSERT INTO PLAYER_POSITIONS (PLAYER_ID, PLAYER_TEAM_ID, POSITION) VALUES (PL_ID,TE_ID,'C');
    INSERT INTO PLAYER_POSITIONS (PLAYER_ID, PLAYER_TEAM_ID, POSITION) VALUES (PL_ID,TE_ID,'SG');
	
    INSERT INTO PLAYER_STATISTICS (G,GS,MP,PTS,TS_PERCENTAGE,FTM,FTA,FT_PERCENTAGE,FGM,FGA,FG_PERCENTAGE
    ,PM3,PA3,P3_PERCENTAGE,PM2,PA2,P2_PERCENTAGE,OREB,OREB_PERCENTAGE,DREB,DREB_PERCENTAGE,TREB,TREB_PERCENTAGE
    ,AST,AST_PERCENTAGE,STL,STL_PERCENTAGE,BLK,BLK_PERCENTAGE,TOV,TOV_PERCENTAGE,USG_PERCENTAGE,OFFWS,DEFWS,WS,WS_48
    ,BPM,VORP,EFG_PERCENTAGE,PF)
    VALUES (18,0,182,22,0.397,4,13,0.308,9,22,0.409,0,0,null,9,22,0.409,9,5.5,38,22.2,47,14.0,3,2.1,2,0.5,4,1.9,9,24.5,8.7,
    -0.2,0.2,-0.1,-0.021,-8.1,-0.3,0.409,20) RETURNING STATS_ID INTO ST_ID;

    INSERT INTO PLAYERS_TEAMS_STATISTICS (PLAYER_ID, TEAM_ID, STATISTICS_ID) VALUES (PL_ID,TE_ID,ST_ID);
	
	INSERT INTO PLAYER_STATISTICS (G,GS,MP,PTS,TS_PERCENTAGE,FTM,FTA,FT_PERCENTAGE,FGM,FGA,FG_PERCENTAGE
    ,PM3,PA3,P3_PERCENTAGE,PM2,PA2,P2_PERCENTAGE,OREB,OREB_PERCENTAGE,DREB,DREB_PERCENTAGE,TREB,TREB_PERCENTAGE
    ,AST,AST_PERCENTAGE,STL,STL_PERCENTAGE,BLK,BLK_PERCENTAGE,TOV,TOV_PERCENTAGE,USG_PERCENTAGE,OFFWS,DEFWS,WS,WS_48
    ,BPM,VORP,EFG_PERCENTAGE,PF)
    VALUES (20,5,182,22,0.397,4,13,0.308,9,24,0.409,0,0,null,9,22,0.409,9,5.5,38,22.2,47,14.0,3,2.1,2,0.5,4,1.9,9,24.5,8.7,
    -0.2,0.2,-0.1,-0.021,-8.1,-0.3,0.409,20) RETURNING STATS_ID INTO ST_ID;

    INSERT INTO PLAYERS_TEAMS_STATISTICS (PLAYER_ID, TEAM_ID, STATISTICS_ID) VALUES (PL_ID,TE_ID,ST_ID);
	
   COMMIT;
END;

