DECLARE
    LOC_ID NUMBER(3);
    AR_ID NUMBER(3);
BEGIN
    SELECT LOCATION_ID
    INTO LOC_ID
    FROM LOCATIONS
    WHERE LOCATION_CITY = 'Atlanta'
    AND LOCATION_STATE = 'Georgia';

    SELECT ARENA_ID
    INTO AR_ID
    FROM ARENAS
    WHERE ARENA_NAME = 'State Farm Arena'
    AND ARENA_LOCATION = LOC_ID;

    INSERT INTO TEAMS (TEAM_NAME,TEAM_ACRONYM,TEAM_ARENA,TEAM_LOCATION)
    VALUES('Atlanta Hawks','ATL',AR_ID,LOC_ID);
    COMMIT;
END;