DECLARE
	LOC_ID NUMBER(3);
BEGIN
SELECT LOCATION_ID
INTO LOC_ID
FROM LOCATIONS
WHERE LOCATION_CITY = 'Charlotte' AND LOCATION_STATE = 'North Carolina';

INSERT INTO ARENAS (ARENA_NAME,ARENA_LOCATION) VALUES ('Spectrum Center',LOC_ID);

COMMIT;
SELECT LOCATION_ID
INTO LOC_ID
FROM LOCATIONS
WHERE LOCATION_CITY = 'Dallas' AND LOCATION_STATE = 'Texas';

INSERT INTO ARENAS (ARENA_NAME,ARENA_LOCATION) VALUES ('American Airlines Center',LOC_ID);

COMMIT;
SELECT LOCATION_ID
INTO LOC_ID
FROM LOCATIONS
WHERE LOCATION_CITY = 'Oakland' AND LOCATION_STATE = 'California';

INSERT INTO ARENAS (ARENA_NAME,ARENA_LOCATION) VALUES ('Oracle Arena',LOC_ID);

COMMIT;
SELECT LOCATION_ID
INTO LOC_ID
FROM LOCATIONS
WHERE LOCATION_CITY = 'Milwaukee' AND LOCATION_STATE = 'Wisconsin';

INSERT INTO ARENAS (ARENA_NAME,ARENA_LOCATION) VALUES ('Fiserv Forum',LOC_ID);

COMMIT;
END;