ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MM-YYYY HH24:MI:SS';

DECLARE
	HOME_TEAM_ID NUMBER(3);
	AWAY_TEAM_ID NUMBER(3);
	GA_ID NUMBER(5);
	GA_STATS NUMBER(6);
BEGIN

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'CHO';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'MIL';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'29/10/2014') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (1,108,'W',41,101,0.406,6,21,0.286,20,29,0.69,15,50,27,8,9,10,20) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (1,106,'L',39,80,0.488,7,14,0.5,21,24,0.875,3,35,25,9,10,14,25) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'GSW';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'CHO';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'15/11/2014') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (9,112,'W',45,87,0.517,11,26,0.423,11,14,0.786,11,51,30,7,3,14,25) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (10,87,'L',32,84,0.381,7,17,0.412,16,28,0.571,10,41,14,5,2,12,13) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'CHO';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'DAL';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'17/11/2014') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (11,80,'L',32,80,0.4,10,22,0.455,6,13,0.462,7,35,22,1,3,11,17) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (11,107,'W',43,84,0.512,10,28,0.357,11,16,0.688,10,50,32,7,4,7,18) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'CHO';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'GSW';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'28/11/2014') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (17,101,'L',38,87,0.437,6,19,0.316,19,23,0.826,8,44,27,4,8,13,14) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (15,106,'W',42,99,0.424,7,26,0.269,15,16,0.938,16,46,28,7,8,12,26) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'MIL';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'DAL';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'3/12/2014') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (20,105,'L',38,73,0.521,7,11,0.636,22,32,0.688,8,39,24,11,2,18,24) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (20,107,'W',42,92,0.457,8,27,0.296,15,22,0.682,17,46,20,8,6,16,23) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'DAL';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'MIL';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'7/12/2014') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (22,125,'W',49,84,0.583,12,31,0.387,15,19,0.789,8,36,29,14,8,11,14) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (22,102,'L',42,84,0.5,4,15,0.267,14,17,0.824,11,36,17,7,4,17,18) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'DAL';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'GSW';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'13/12/2014') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (25,98,'L',36,89,0.404,5,25,0.2,21,30,0.7,17,53,14,11,0,15,23) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (22,105,'W',37,83,0.446,10,32,0.313,21,27,0.778,9,45,21,7,7,13,24) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'MIL';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'CHO';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'23/12/2014') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (29,101,'L',39,82,0.476,8,21,0.381,15,20,0.75,9,40,25,7,6,20,25) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (29,108,'W',36,82,0.439,8,21,0.381,28,36,0.778,11,43,21,6,5,12,21) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'CHO';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'MIL';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'29/12/2014') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (32,94,'L',33,90,0.367,7,25,0.28,21,26,0.808,9,48,20,13,9,17,20) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (32,104,'W',40,85,0.471,6,21,0.286,18,21,0.857,2,42,21,8,10,19,25) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'GSW';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'DAL';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'4/2/2015') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (47,128,'W',45,86,0.523,19,38,0.5,19,25,0.76,10,46,29,5,5,13,22) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (51,114,'L',41,98,0.418,10,30,0.333,22,28,0.786,14,42,24,8,1,8,19) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'DAL';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'CHO';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'22/2/2015') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (58,92,'W',36,78,0.462,5,18,0.278,15,19,0.789,6,49,20,7,6,15,16) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (54,81,'L',33,90,0.367,6,19,0.316,9,13,0.692,13,47,20,10,2,14,20) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'GSW';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'MIL';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'4/3/2015') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (59,102,'W',37,73,0.507,14,34,0.412,14,25,0.56,4,34,30,16,8,16,24) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (61,93,'L',34,80,0.425,5,14,0.357,20,25,0.8,16,47,17,11,1,23,19) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'GSW';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'DAL';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'6/3/2015') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (60,104,'W',38,81,0.469,11,23,0.478,17,19,0.895,9,51,28,5,11,22,21) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (64,89,'L',32,87,0.368,6,20,0.3,19,26,0.731,3,34,17,15,1,11,20) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'MIL';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'GSW';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'28/3/2015') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (73,95,'L',33,87,0.379,2,15,0.133,27,32,0.844,15,42,24,14,5,15,20) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (73,108,'W',42,82,0.512,12,25,0.48,12,14,0.857,7,45,27,7,8,22,23) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'DAL';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'GSW';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'4/4/2015') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (77,110,'L',34,80,0.425,3,16,0.188,39,54,0.722,10,44,14,6,2,16,23) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (76,123,'W',43,95,0.453,14,36,0.389,23,32,0.719,17,55,28,12,4,14,37) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'DAL';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'CHO';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'5/11/2015') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (5,94,'L',32,82,0.39,6,29,0.207,24,27,0.889,8,44,17,8,2,13,13) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (5,108,'W',44,89,0.494,6,27,0.222,14,17,0.824,8,48,19,8,6,11,25) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'CHO';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'MIL';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'29/11/2015') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (17,87,'W',27,70,0.386,15,31,0.484,18,22,0.818,7,43,20,6,6,13,16) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (17,82,'L',33,82,0.402,8,28,0.286,8,14,0.571,13,46,25,9,2,14,24) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'CHO';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'GSW';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'2/12/2015') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (18,99,'L',35,94,0.372,9,31,0.29,20,30,0.667,13,41,19,10,7,8,13) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (20,116,'W',46,88,0.523,16,34,0.471,8,11,0.727,11,53,31,2,9,18,23) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'MIL';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'GSW';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'12/12/2015') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (25,108,'W',44,90,0.489,6,14,0.429,14,18,0.778,8,44,31,12,4,16,24) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (25,95,'L',36,89,0.404,6,27,0.222,17,25,0.68,15,49,23,9,8,16,20) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'GSW';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'MIL';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'18/12/2015') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (27,121,'W',42,87,0.483,9,26,0.346,28,37,0.757,15,46,31,7,4,15,22) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (28,112,'L',42,91,0.462,4,18,0.222,24,28,0.857,14,41,25,6,7,16,29) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'DAL';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'MIL';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'28/12/2015') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (31,103,'W',38,84,0.452,10,22,0.455,17,26,0.654,6,34,25,9,2,4,15) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (32,93,'L',38,79,0.481,4,14,0.286,13,15,0.867,9,52,14,4,5,17,22) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'DAL';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'GSW';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'30/12/2015') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (32,114,'W',42,82,0.512,14,27,0.519,16,20,0.8,12,52,20,6,4,15,19) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (31,91,'L',33,81,0.407,7,19,0.368,18,24,0.75,8,37,20,9,0,12,18) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'GSW';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'CHO';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'4/1/2016') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (34,111,'W',45,87,0.517,15,34,0.441,6,6,1,3,37,32,4,9,11,19) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (34,101,'L',38,86,0.442,7,21,0.333,18,19,0.947,8,41,15,7,1,11,12) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'MIL';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'DAL';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'8/1/2016') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (38,96,'W',37,80,0.463,4,9,0.444,18,29,0.621,15,43,24,11,4,15,20) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (37,95,'L',35,84,0.417,14,44,0.318,11,16,0.688,16,42,27,6,5,16,21) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'CHO';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'MIL';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'16/1/2016') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (40,92,'L',33,87,0.379,9,36,0.25,17,22,0.773,13,35,27,8,2,5,20) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (43,105,'W',39,72,0.542,5,12,0.417,22,26,0.846,6,46,23,3,11,15,15) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'GSW';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'DAL';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'27/1/2016') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (46,127,'W',47,81,0.58,14,29,0.483,19,21,0.905,7,40,33,5,4,9,18) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (48,107,'L',44,87,0.506,11,31,0.355,8,12,0.667,8,34,20,4,0,10,21) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'MIL';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'CHO';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'19/2/2016') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (55,95,'L',36,81,0.444,7,19,0.368,16,21,0.762,12,47,22,7,11,22,17) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (54,98,'W',37,86,0.43,9,31,0.29,15,18,0.833,8,37,13,13,6,17,16) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'CHO';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'DAL';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'14/3/2016') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (66,96,'L',32,76,0.421,10,30,0.333,22,34,0.647,7,40,18,9,7,15,16) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (67,107,'W',42,87,0.483,9,30,0.3,14,18,0.778,6,42,30,9,6,14,26) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'DAL';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'GSW';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'18/3/2016') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (69,112,'L',41,93,0.441,9,29,0.31,21,22,0.955,11,46,25,4,8,12,15) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (68,130,'W',48,95,0.505,22,38,0.579,12,14,0.857,5,42,35,8,7,12,21) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'GSW';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'DAL';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'25/3/2016') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (72,128,'W',43,88,0.489,21,45,0.467,21,23,0.913,7,40,30,8,10,7,16) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (72,120,'L',43,96,0.448,18,35,0.514,16,21,0.762,15,51,31,3,6,11,19) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'MIL';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'CHO';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'26/3/2016') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (74,91,'L',37,84,0.44,4,15,0.267,13,15,0.867,9,37,26,6,3,9,16) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (73,115,'W',41,74,0.554,16,29,0.552,17,21,0.81,5,35,30,6,8,8,11) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'MIL';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'CHO';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'26/10/2016') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (1,96,'L',39,92,0.424,3,16,0.188,15,20,0.75,10,46,23,4,5,8,22) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (1,107,'W',40,89,0.449,7,23,0.304,20,24,0.833,11,51,27,5,10,10,22) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'DAL';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'MIL';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'6/11/2016') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (6,86,'W',33,88,0.375,9,38,0.237,11,12,0.917,10,46,14,12,2,15,20) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (7,75,'L',30,82,0.366,6,29,0.207,9,12,0.75,9,51,14,11,2,27,26) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'GSW';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'DAL';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'9/11/2016') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (8,116,'W',43,74,0.581,17,33,0.515,13,22,0.591,5,39,33,3,5,15,22) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (8,95,'L',34,86,0.395,6,28,0.214,21,28,0.75,13,42,20,10,2,7,20) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'MIL';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'GSW';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'19/11/2016') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (12,121,'L',46,89,0.517,10,20,0.5,19,25,0.76,10,41,27,7,1,13,23) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (13,124,'W',42,95,0.442,14,38,0.368,26,32,0.813,18,45,30,8,5,12,25) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'CHO';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'DAL';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'1/12/2016') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (19,97,'W',35,74,0.473,5,18,0.278,22,31,0.71,4,39,24,5,6,10,18) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (18,87,'L',32,86,0.372,9,31,0.29,14,18,0.778,9,41,18,6,2,11,25) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'DAL';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'CHO';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'5/12/2016') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (20,101,'L',37,89,0.416,13,36,0.361,14,18,0.778,9,35,23,4,2,7,19) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (21,109,'W',40,79,0.506,3,18,0.167,26,28,0.929,9,53,21,2,5,12,19) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'GSW';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'DAL';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'30/12/2016') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (34,108,'W',42,84,0.5,11,33,0.333,13,15,0.867,4,43,31,5,4,13,12) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (34,99,'L',39,93,0.419,8,32,0.25,13,15,0.867,11,40,22,11,7,10,12) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'CHO';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'GSW';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'25/1/2017') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (46,103,'L',38,92,0.413,7,23,0.304,20,21,0.952,12,43,26,6,6,14,18) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (46,113,'W',39,82,0.476,11,28,0.393,24,27,0.889,5,41,23,7,14,12,19) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'GSW';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'CHO';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'1/2/2017') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (49,126,'W',47,96,0.49,21,48,0.438,11,14,0.786,9,47,35,9,13,10,18) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (50,111,'L',39,88,0.443,9,31,0.29,24,26,0.923,6,45,33,4,3,10,14) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'GSW';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'MIL';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'18/3/2017') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (69,117,'W',45,75,0.6,12,23,0.522,15,19,0.789,6,44,30,5,6,12,16) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (69,92,'L',36,89,0.404,9,27,0.333,11,14,0.786,12,35,19,8,7,11,17) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'DAL';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'GSW';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'21/3/2017') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (70,87,'L',33,92,0.359,11,34,0.324,10,12,0.833,13,39,24,8,2,11,14) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (71,112,'W',43,78,0.551,13,30,0.433,13,16,0.813,4,46,34,10,2,16,20) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'CHO';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'MIL';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'28/3/2017') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (74,108,'L',39,80,0.488,7,28,0.25,23,29,0.793,5,31,25,7,1,2,12) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (74,118,'W',46,74,0.622,14,30,0.467,12,17,0.706,3,42,31,1,3,14,26) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'MIL';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'DAL';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'2/4/2017') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (77,105,'L',39,77,0.506,12,34,0.353,15,18,0.833,4,33,25,9,3,13,20) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (76,109,'W',38,73,0.521,14,36,0.389,19,20,0.95,4,30,25,7,1,13,18) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'MIL';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'CHO';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'10/4/2017') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (81,89,'W',35,78,0.449,16,27,0.593,3,5,0.6,8,46,28,4,3,16,14) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (81,79,'L',33,81,0.407,5,18,0.278,8,13,0.615,7,39,21,11,5,9,10) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'DAL';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'GSW';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'23/10/2017') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (4,103,'L',38,96,0.396,9,29,0.31,18,30,0.6,14,42,21,11,0,12,20) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (4,133,'W',48,86,0.558,15,39,0.385,22,26,0.846,10,50,33,6,8,16,23) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'MIL';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'CHO';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'23/10/2017') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (4,103,'W',40,85,0.471,9,26,0.346,14,16,0.875,5,42,24,8,4,13,27) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (3,94,'L',33,78,0.423,7,26,0.269,21,36,0.583,10,48,17,3,5,14,21) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'CHO';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'MIL';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'1/11/2017') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (8,126,'W',45,84,0.536,14,25,0.56,22,29,0.759,7,41,21,5,3,11,18) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (8,121,'L',45,91,0.495,19,36,0.528,12,15,0.8,9,40,29,3,3,14,25) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'DAL';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'MIL';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'18/11/2017') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (17,111,'W',38,79,0.481,19,38,0.5,16,19,0.842,7,49,27,7,2,16,26) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (15,79,'L',28,74,0.378,6,25,0.24,17,31,0.548,8,38,13,8,5,12,25) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'CHO';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'GSW';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'6/12/2017') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (23,87,'L',34,97,0.351,6,19,0.316,13,17,0.765,14,49,17,5,3,12,13) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (26,101,'W',40,84,0.476,11,30,0.367,10,13,0.769,8,47,26,8,12,15,20) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'MIL';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'DAL';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'8/12/2017') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (24,109,'W',36,79,0.456,8,24,0.333,29,34,0.853,7,40,20,10,6,10,24) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (26,102,'L',35,75,0.467,10,24,0.417,22,26,0.846,4,36,18,6,2,11,22) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'GSW';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'DAL';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'14/12/2017') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (29,112,'W',47,78,0.603,11,22,0.5,7,9,0.778,4,41,35,7,4,16,22) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (29,97,'L',37,82,0.451,10,29,0.345,13,17,0.765,8,31,25,7,1,11,16) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'MIL';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'CHO';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'22/12/2017') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (30,109,'W',41,87,0.471,8,29,0.276,19,23,0.826,6,43,27,7,5,7,16) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (32,104,'L',39,88,0.443,12,26,0.462,14,17,0.824,9,43,21,4,7,9,18) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'CHO';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'MIL';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'23/12/2017') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (33,111,'W',36,74,0.486,9,21,0.429,30,40,0.75,9,43,22,2,7,16,20) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (31,106,'L',42,87,0.483,8,26,0.308,14,17,0.824,7,35,25,4,2,9,32) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'GSW';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'CHO';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'29/12/2017') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (36,100,'L',40,87,0.46,8,22,0.364,12,13,0.923,8,43,32,6,5,17,25) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (35,111,'W',41,89,0.461,6,20,0.3,23,34,0.676,13,47,27,12,6,10,10) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'DAL';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'GSW';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'3/1/2018') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (39,122,'L',43,90,0.478,19,43,0.442,17,22,0.773,7,40,29,6,2,12,17) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (38,125,'W',48,91,0.527,13,32,0.406,16,19,0.842,7,46,36,8,7,14,21) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'CHO';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'DAL';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'10/1/2018') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (39,111,'L',43,84,0.512,10,26,0.385,15,30,0.5,4,43,16,6,5,11,22) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (43,115,'W',39,83,0.47,15,36,0.417,22,28,0.786,3,39,23,7,7,8,22) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'MIL';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'GSW';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'12/1/2018') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (41,94,'L',36,85,0.424,11,28,0.393,11,12,0.917,8,33,21,9,6,12,20) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (43,108,'W',44,79,0.557,5,15,0.333,15,18,0.833,10,43,28,7,3,11,13) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'GSW';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'DAL';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'8/2/2018') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (55,121,'W',45,88,0.511,14,29,0.483,17,20,0.85,18,51,37,6,7,16,18) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (55,103,'L',40,92,0.435,9,37,0.243,14,17,0.824,9,34,19,15,7,10,16) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'DAL';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'CHO';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'24/3/2018') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (73,98,'L',36,91,0.396,12,41,0.293,14,19,0.737,5,52,22,10,6,12,22) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (74,102,'W',35,92,0.38,12,25,0.48,20,29,0.69,13,62,21,10,4,13,14) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

SELECT TEAM_ID
INTO HOME_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'GSW';

SELECT TEAM_ID
INTO AWAY_TEAM_ID
FROM TEAMS
WHERE TEAM_ACRONYM = 'MIL';

INSERT INTO GAMES (HOME_TEAM,AWAY_TEAM,GAME_DATE) VALUES (HOME_TEAM_ID,AWAY_TEAM_ID,'29/3/2018') RETURNING GAME_ID INTO GA_ID;

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (75,107,'L',41,75,0.547,10,20,0.5,15,15,1,2,31,26,10,7,18,19) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,HOME_TEAM_ID,GA_STATS);

INSERT INTO GAME_STATISTICS (GAME_NUMBER,POINTS,TEAM_RESULT,FIELD_GOALS,FIELD_GOALS_ATTEMPTED,FIELD_GOALS_PERCENTAGE,X3POINTSHOTS,X3POINTSHOTS_ATTEMPTED,X3POINTSHOTS_PERCENTAGE,FREETHROWS,FREETHROWS_ATTEMPTED,FREETHROWS_PERCENTAGE,OFFREBOUNDS,TOTALREBOUNDS,ASSISTS,STEALS,BLOCKS,TURNOVERS,TOTALFOULS) VALUES (75,116,'W',48,87,0.552,11,20,0.55,9,10,0.9,7,36,30,16,3,15,17) RETURNING STATS_ID INTO GA_STATS;

INSERT INTO GAMES_TEAMS_STATISTICS (GAME_ID,TEAM_ID,STATS_ID) VALUES (GA_ID,AWAY_TEAM_ID,GA_STATS);

COMMIT;

END;
