INSERT INTO LOCATIONS (LOCATION_CITY,LOCATION_STATE) VALUES ('Charlotte','North Carolina');
INSERT INTO LOCATIONS (LOCATION_CITY,LOCATION_STATE) VALUES ('Dallas','Texas');
INSERT INTO LOCATIONS (LOCATION_CITY,LOCATION_STATE) VALUES ('Oakland','California');
INSERT INTO LOCATIONS (LOCATION_CITY,LOCATION_STATE) VALUES ('Milwaukee','Wisconsin');
COMMIT;
