DECLARE
	LOC_ID NUMBER(3);
	AR_ID NUMBER(3);
BEGIN
SELECT LOCATION_ID
INTO LOC_ID
FROM LOCATIONS
WHERE LOCATION_CITY = 'Charlotte' AND LOCATION_STATE = 'North Carolina';

SELECT ARENA_ID
INTO AR_ID
FROM ARENAS
WHERE ARENA_NAME = 'Spectrum Center' AND ARENA_LOCATION = LOC_ID;

INSERT INTO TEAMS (TEAM_NAME,TEAM_ACRONYM,TEAM_ARENA,TEAM_LOCATION) VALUES ('Charlotte Hornets','CHO',AR_ID,LOC_ID);
COMMIT;
SELECT LOCATION_ID
INTO LOC_ID
FROM LOCATIONS
WHERE LOCATION_CITY = 'Dallas' AND LOCATION_STATE = 'Texas';

SELECT ARENA_ID
INTO AR_ID
FROM ARENAS
WHERE ARENA_NAME = 'American Airlines Center' AND ARENA_LOCATION = LOC_ID;

INSERT INTO TEAMS (TEAM_NAME,TEAM_ACRONYM,TEAM_ARENA,TEAM_LOCATION) VALUES ('Dallas Mavericks','DAL',AR_ID,LOC_ID);
COMMIT;
SELECT LOCATION_ID
INTO LOC_ID
FROM LOCATIONS
WHERE LOCATION_CITY = 'Oakland' AND LOCATION_STATE = 'California';

SELECT ARENA_ID
INTO AR_ID
FROM ARENAS
WHERE ARENA_NAME = 'Oracle Arena' AND ARENA_LOCATION = LOC_ID;

INSERT INTO TEAMS (TEAM_NAME,TEAM_ACRONYM,TEAM_ARENA,TEAM_LOCATION) VALUES ('Golden State Warriors','GSW',AR_ID,LOC_ID);
COMMIT;
SELECT LOCATION_ID
INTO LOC_ID
FROM LOCATIONS
WHERE LOCATION_CITY = 'Milwaukee' AND LOCATION_STATE = 'Wisconsin';

SELECT ARENA_ID
INTO AR_ID
FROM ARENAS
WHERE ARENA_NAME = 'Fiserv Forum' AND ARENA_LOCATION = LOC_ID;

INSERT INTO TEAMS (TEAM_NAME,TEAM_ACRONYM,TEAM_ARENA,TEAM_LOCATION) VALUES ('Milwaukee Bucks','MIL',AR_ID,LOC_ID);
COMMIT;
END;